server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zoostudio_user?useUnicode=true&characterEncoding=UTF-8
    username: gjw
    password: w45456306
    driver-class-name: com.mysql.cj.jdbc.Driver
  jap:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
    mode: LEGACYHTML5  #不严格的html检查




---
spring:
  profiles: dev
server:
  port: 8070







